name: DauntlessWeapons
version: '${project.version}'
main: com.randombananazz.minecraft.DauntlessWeapons
api-version: 1.17
commands:
  weapon:
    description: Gives a specific weapon with a specified owner.
